name: 'downstream_project'
version: '1.0.0'
config-version: 2

profile: 'downstream_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  downstream_project:
    +materialized: table
